services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:80"

    volumes:
      - .:/var/www/html
      - laravel_storage:/var/www/html/storage

    restart: unless-stopped

volumes:
  laravel_storage: